### ISSUE TITLE
Missing `../list/celeba_2d_train_filelist.txt` file for CelebA dataset

### ISSUE THREAD

**Issue by jyhong836** [jeremy43/Private_kNN#4]
Hi authors,

Thank you for the awesome work. When I try to run `knn_attribute.py`, it turns out that the file `../list/celeba_2d_train_filelist.txt` is missing. It is not in the standard files of CelebA, where CelebA only provides attribute file instead of filelist file. It would be helpful if you can upload the file for reproducing results.

Thanks

**Comment by liyuntong9** [comment]
I also meet the same problem. How can I solve it?

**Comment by jyhong836** [comment]
I don’t know either. I try to implement CelebA experiment by myself.

**Comment by jeremy43** [comment]
Hi, I just uploaded the train_filelist.txt, which is the label file from the original dataset. Please let me know if there are other issues.
